//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIASSImportOrganoclorurati.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USER ID=SIASS;PASSWORD=SIASS;DATA SOURCE=localhost:1521/xe")]
        public string StringaConnessioneDB {
            get {
                return ((string)(this["StringaConnessioneDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\gianky\\Documents\\Visual Studio 2022\\Projects\\SIASS\\SIASS\\File\\Importazio" +
            "niOrganoclorurati\\")]
        public string PercorsoFileDaImportare {
            get {
                return ((string)(this["PercorsoFileDaImportare"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\gianky\\Documents\\Visual Studio 2022\\Projects\\SIASS\\SIASS\\File\\Importazio" +
            "niOrganoclorurati\\Rapporti\\")]
        public string PercorsoReportImportazione {
            get {
                return ((string)(this["PercorsoReportImportazione"]));
            }
        }
    }
}
