//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIASS.ANSOLOServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.arpal.org/ansolo", ConfigurationName="ANSOLOServiceReference.AnsoloWebServiceSoap")]
    public interface AnsoloWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.arpal.org/ansolo/InserimentoUtenteGSO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InserimentoUtenteGSO(string cognome, string nome, int idUtenteGSO, bool ignorareOmonimie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.arpal.org/ansolo/InserimentoUtenteGSO", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InserimentoUtenteGSOAsync(string cognome, string nome, int idUtenteGSO, bool ignorareOmonimie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.arpal.org/ansolo/RicercaSoggetti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RicercaSoggetti(string cognomeNomeMatricolaRagioneSociale, string codiceTipologia, bool ricercaParziale, int numeroMassimoRisultati, bool soloValidi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.arpal.org/ansolo/RicercaSoggetti", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RicercaSoggettiAsync(string cognomeNomeMatricolaRagioneSociale, string codiceTipologia, bool ricercaParziale, int numeroMassimoRisultati, bool soloValidi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.arpal.org/ansolo/RicercaSoggettiCognomeNome", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RicercaSoggettiCognomeNome(string cognome, string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.arpal.org/ansolo/RicercaSoggettiCognomeNome", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RicercaSoggettiCognomeNomeAsync(string cognome, string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.arpal.org/ansolo/DettagliSoggetto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DettagliSoggetto(int IDAnagrafica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.arpal.org/ansolo/DettagliSoggetto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DettagliSoggettoAsync(int IDAnagrafica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.arpal.org/ansolo/IdAnsoloPerIdUtenteGSO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int IdAnsoloPerIdUtenteGSO(int IDUtenteGSO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.arpal.org/ansolo/IdAnsoloPerIdUtenteGSO", ReplyAction="*")]
        System.Threading.Tasks.Task<int> IdAnsoloPerIdUtenteGSOAsync(int IDUtenteGSO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.arpal.org/ansolo/ElencoUtentiValidi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ElencoUtentiValidi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.arpal.org/ansolo/ElencoUtentiValidi", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ElencoUtentiValidiAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AnsoloWebServiceSoapChannel : SIASS.ANSOLOServiceReference.AnsoloWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnsoloWebServiceSoapClient : System.ServiceModel.ClientBase<SIASS.ANSOLOServiceReference.AnsoloWebServiceSoap>, SIASS.ANSOLOServiceReference.AnsoloWebServiceSoap {
        
        public AnsoloWebServiceSoapClient() {
        }
        
        public AnsoloWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnsoloWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnsoloWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnsoloWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InserimentoUtenteGSO(string cognome, string nome, int idUtenteGSO, bool ignorareOmonimie) {
            return base.Channel.InserimentoUtenteGSO(cognome, nome, idUtenteGSO, ignorareOmonimie);
        }
        
        public System.Threading.Tasks.Task<int> InserimentoUtenteGSOAsync(string cognome, string nome, int idUtenteGSO, bool ignorareOmonimie) {
            return base.Channel.InserimentoUtenteGSOAsync(cognome, nome, idUtenteGSO, ignorareOmonimie);
        }
        
        public System.Data.DataSet RicercaSoggetti(string cognomeNomeMatricolaRagioneSociale, string codiceTipologia, bool ricercaParziale, int numeroMassimoRisultati, bool soloValidi) {
            return base.Channel.RicercaSoggetti(cognomeNomeMatricolaRagioneSociale, codiceTipologia, ricercaParziale, numeroMassimoRisultati, soloValidi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RicercaSoggettiAsync(string cognomeNomeMatricolaRagioneSociale, string codiceTipologia, bool ricercaParziale, int numeroMassimoRisultati, bool soloValidi) {
            return base.Channel.RicercaSoggettiAsync(cognomeNomeMatricolaRagioneSociale, codiceTipologia, ricercaParziale, numeroMassimoRisultati, soloValidi);
        }
        
        public System.Data.DataSet RicercaSoggettiCognomeNome(string cognome, string nome) {
            return base.Channel.RicercaSoggettiCognomeNome(cognome, nome);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RicercaSoggettiCognomeNomeAsync(string cognome, string nome) {
            return base.Channel.RicercaSoggettiCognomeNomeAsync(cognome, nome);
        }
        
        public System.Data.DataSet DettagliSoggetto(int IDAnagrafica) {
            return base.Channel.DettagliSoggetto(IDAnagrafica);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DettagliSoggettoAsync(int IDAnagrafica) {
            return base.Channel.DettagliSoggettoAsync(IDAnagrafica);
        }
        
        public int IdAnsoloPerIdUtenteGSO(int IDUtenteGSO) {
            return base.Channel.IdAnsoloPerIdUtenteGSO(IDUtenteGSO);
        }
        
        public System.Threading.Tasks.Task<int> IdAnsoloPerIdUtenteGSOAsync(int IDUtenteGSO) {
            return base.Channel.IdAnsoloPerIdUtenteGSOAsync(IDUtenteGSO);
        }
        
        public System.Data.DataSet ElencoUtentiValidi() {
            return base.Channel.ElencoUtentiValidi();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ElencoUtentiValidiAsync() {
            return base.Channel.ElencoUtentiValidiAsync();
        }
    }
}
