/*
 * Nome del progetto: SIASS
 * Copyright (C) 2025 Agenzia regionale per la protezione dell'ambiente ligure
 *
 * Questo programma è software libero: puoi ridistribuirlo e/o modificarlo
 * secondo i termini della GNU Affero General Public License pubblicata dalla
 * Free Software Foundation, sia la versione 3 della licenza, sia (a tua scelta)
 * qualsiasi versione successiva.
 *
 * Questo programma è distribuito nella speranza che possa essere utile,
 * ma SENZA ALCUNA GARANZIA; senza nemmeno la garanzia implicita di
 * COMMERCIABILITÀ o IDONEITÀ PER UNO SCOPO PARTICOLARE. Vedi la
 * GNU Affero General Public License per ulteriori dettagli.
 *
 * Dovresti aver ricevuto una copia della GNU Affero General Public License
 * insieme a questo programma. In caso contrario, vedi <https://www.gnu.org/licenses/>.
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thermo.com/informatics/xmlns/limswebservice", ConfigurationName="ILIMSWebService")]
public interface ILIMSWebService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/Process", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/ProcessRes" +
        "ponse")]
    string Process(string request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/Process", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/ProcessRes" +
        "ponse")]
    System.Threading.Tasks.Task<string> ProcessAsync(string request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/CheckAuth", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/CheckAuthR" +
        "esponse")]
    string CheckAuth();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/CheckAuth", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/CheckAuthR" +
        "esponse")]
    System.Threading.Tasks.Task<string> CheckAuthAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/GetAllLogFiles", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/GetAllLogF" +
        "ilesResponse")]
    object GetAllLogFiles();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/GetAllLogFiles", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/GetAllLogF" +
        "ilesResponse")]
    System.Threading.Tasks.Task<object> GetAllLogFilesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/EraseAllLogFiles", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/EraseAllLo" +
        "gFilesResponse")]
    string EraseAllLogFiles();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/EraseAllLogFiles", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/EraseAllLo" +
        "gFilesResponse")]
    System.Threading.Tasks.Task<string> EraseAllLogFilesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/GetSingleLogFile", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/GetSingleL" +
        "ogFileResponse")]
    object GetSingleLogFile(string transaction, string direction);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/GetSingleLogFile", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/GetSingleL" +
        "ogFileResponse")]
    System.Threading.Tasks.Task<object> GetSingleLogFileAsync(string transaction, string direction);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/LogSOAPMessages", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/LogSOAPMes" +
        "sagesResponse")]
    bool LogSOAPMessages(bool logging);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/LogSOAPMessages", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/LogSOAPMes" +
        "sagesResponse")]
    System.Threading.Tasks.Task<bool> LogSOAPMessagesAsync(bool logging);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/ViewLogStatus", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/ViewLogSta" +
        "tusResponse")]
    bool ViewLogStatus();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/ViewLogStatus", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/ViewLogSta" +
        "tusResponse")]
    System.Threading.Tasks.Task<bool> ViewLogStatusAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILIMSWebServiceChannel : ILIMSWebService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LIMSWebServiceClient : System.ServiceModel.ClientBase<ILIMSWebService>, ILIMSWebService
{
    
    public LIMSWebServiceClient()
    {
    }
    
    public LIMSWebServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LIMSWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LIMSWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LIMSWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Process(string request)
    {
        return base.Channel.Process(request);
    }
    
    public System.Threading.Tasks.Task<string> ProcessAsync(string request)
    {
        return base.Channel.ProcessAsync(request);
    }
    
    public string CheckAuth()
    {
        return base.Channel.CheckAuth();
    }
    
    public System.Threading.Tasks.Task<string> CheckAuthAsync()
    {
        return base.Channel.CheckAuthAsync();
    }
    
    public object GetAllLogFiles()
    {
        return base.Channel.GetAllLogFiles();
    }
    
    public System.Threading.Tasks.Task<object> GetAllLogFilesAsync()
    {
        return base.Channel.GetAllLogFilesAsync();
    }
    
    public string EraseAllLogFiles()
    {
        return base.Channel.EraseAllLogFiles();
    }
    
    public System.Threading.Tasks.Task<string> EraseAllLogFilesAsync()
    {
        return base.Channel.EraseAllLogFilesAsync();
    }
    
    public object GetSingleLogFile(string transaction, string direction)
    {
        return base.Channel.GetSingleLogFile(transaction, direction);
    }
    
    public System.Threading.Tasks.Task<object> GetSingleLogFileAsync(string transaction, string direction)
    {
        return base.Channel.GetSingleLogFileAsync(transaction, direction);
    }
    
    public bool LogSOAPMessages(bool logging)
    {
        return base.Channel.LogSOAPMessages(logging);
    }
    
    public System.Threading.Tasks.Task<bool> LogSOAPMessagesAsync(bool logging)
    {
        return base.Channel.LogSOAPMessagesAsync(logging);
    }
    
    public bool ViewLogStatus()
    {
        return base.Channel.ViewLogStatus();
    }
    
    public System.Threading.Tasks.Task<bool> ViewLogStatusAsync()
    {
        return base.Channel.ViewLogStatusAsync();
    }
}
