//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIASS.GSOServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GSOServiceReference.GsoWebServicesSoap")]
    public interface GsoWebServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Logon(string sUserName, string sPassword, string sApplication, bool bTrusted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logon", ReplyAction="*")]
        System.Threading.Tasks.Task<int> LogonAsync(string sUserName, string sPassword, string sApplication, bool bTrusted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetApplicationList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetApplicationList(int nUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetApplicationList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetApplicationListAsync(int nUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUserListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUserList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllUserList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUserList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllUserListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUserListDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllUserListDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUserListDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllUserListDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAppUserProfiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAppUserProfiles(int nUserId, string sApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAppUserProfiles", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAppUserProfilesAsync(int nUserId, string sApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetApplicationUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetApplicationUsers(string sApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetApplicationUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetApplicationUsersAsync(string sApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUtentiSostituti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUtentiSostituti(int nUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUtentiSostituti", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUtentiSostitutiAsync(int nUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUtentiSostituitiAppl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUtentiSostituitiAppl(int nUserId, string sApplicazione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUtentiSostituitiAppl", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUtentiSostituitiApplAsync(int nUserId, string sApplicazione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResponsabiliStrutture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetResponsabiliStrutture();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResponsabiliStrutture", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetResponsabiliStruttureAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResponsabiliStruttureConDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetResponsabiliStruttureConDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResponsabiliStruttureConDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetResponsabiliStruttureConDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStruttureConDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetStruttureConDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStruttureConDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetStruttureConDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStruttureUtente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetStruttureUtente(int nUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStruttureUtente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetStruttureUtenteAsync(int nUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUtentiStruttura", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUtentiStruttura(int nIdStruttura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUtentiStruttura", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUtentiStrutturaAsync(int nIdStruttura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStruttureUtente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllStruttureUtente(int nUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStruttureUtente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllStruttureUtenteAsync(int nUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStruttureUtenteConDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllStruttureUtenteConDate(int nUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStruttureUtenteConDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllStruttureUtenteConDateAsync(int nUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStruttureSenzaResponsabile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetStruttureSenzaResponsabile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStruttureSenzaResponsabile", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetStruttureSenzaResponsabileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDepAppProfiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserDepAppProfiles(int nUserId, string sApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDepAppProfiles", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUserDepAppProfilesAsync(int nUserId, string sApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUtentiStruttura", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllUtentiStruttura(int nIdStruttura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUtentiStruttura", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllUtentiStrutturaAsync(int nIdStruttura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUtentiInterniStruttura", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllUtentiInterniStruttura(int nIdStruttura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUtentiInterniStruttura", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllUtentiInterniStrutturaAsync(int nIdStruttura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUtentiInterniStrutturaPerData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllUtentiInterniStrutturaPerData(int nIdStruttura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUtentiInterniStrutturaPerData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllUtentiInterniStrutturaPerDataAsync(int nIdStruttura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUtentiPerFunzione", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUtentiPerFunzione(string sCodElFunz);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUtentiPerFunzione", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUtentiPerFunzioneAsync(string sCodElFunz);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFunzioniPerUtente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetFunzioniPerUtente(int nIdUtente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFunzioniPerUtente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetFunzioniPerUtenteAsync(int nIdUtente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUtentePerCodice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUtentePerCodice(int nIdUtente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUtentePerCodice", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUtentePerCodiceAsync(int nIdUtente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosOrgStrutOrg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPosOrgStrutOrg(int nIdPosOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosOrgStrutOrg", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPosOrgStrutOrgAsync(int nIdPosOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStrutture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllStrutture();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStrutture", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllStruttureAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStrutture_Tutte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllStrutture_Tutte();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStrutture_Tutte", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllStrutture_TutteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUffici", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllUffici();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUffici", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllUfficiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSedeUtentePerCodice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSedeUtentePerCodice(int nIdUtente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSedeUtentePerCodice", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSedeUtentePerCodiceAsync(int nIdUtente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSottopostiDaResponsabile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSottopostiDaResponsabile(int nIdUtente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSottopostiDaResponsabile", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSottopostiDaResponsabileAsync(int nIdUtente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSedi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllSedi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSedi", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllSediAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStruttureSede", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetStruttureSede(int nIdSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStruttureSede", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetStruttureSedeAsync(int nIdSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStruttureResponsabile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllStruttureResponsabile(int nUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStruttureResponsabile", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllStruttureResponsabileAsync(int nUserId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GsoWebServicesSoapChannel : SIASS.GSOServiceReference.GsoWebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GsoWebServicesSoapClient : System.ServiceModel.ClientBase<SIASS.GSOServiceReference.GsoWebServicesSoap>, SIASS.GSOServiceReference.GsoWebServicesSoap {
        
        public GsoWebServicesSoapClient() {
        }
        
        public GsoWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GsoWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GsoWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GsoWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Logon(string sUserName, string sPassword, string sApplication, bool bTrusted) {
            return base.Channel.Logon(sUserName, sPassword, sApplication, bTrusted);
        }
        
        public System.Threading.Tasks.Task<int> LogonAsync(string sUserName, string sPassword, string sApplication, bool bTrusted) {
            return base.Channel.LogonAsync(sUserName, sPassword, sApplication, bTrusted);
        }
        
        public System.Data.DataSet GetApplicationList(int nUserId) {
            return base.Channel.GetApplicationList(nUserId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetApplicationListAsync(int nUserId) {
            return base.Channel.GetApplicationListAsync(nUserId);
        }
        
        public System.Data.DataSet GetUserList() {
            return base.Channel.GetUserList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUserListAsync() {
            return base.Channel.GetUserListAsync();
        }
        
        public System.Data.DataSet GetAllUserList() {
            return base.Channel.GetAllUserList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllUserListAsync() {
            return base.Channel.GetAllUserListAsync();
        }
        
        public System.Data.DataSet GetAllUserListDate() {
            return base.Channel.GetAllUserListDate();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllUserListDateAsync() {
            return base.Channel.GetAllUserListDateAsync();
        }
        
        public System.Data.DataSet GetAppUserProfiles(int nUserId, string sApplication) {
            return base.Channel.GetAppUserProfiles(nUserId, sApplication);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAppUserProfilesAsync(int nUserId, string sApplication) {
            return base.Channel.GetAppUserProfilesAsync(nUserId, sApplication);
        }
        
        public System.Data.DataSet GetApplicationUsers(string sApplication) {
            return base.Channel.GetApplicationUsers(sApplication);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetApplicationUsersAsync(string sApplication) {
            return base.Channel.GetApplicationUsersAsync(sApplication);
        }
        
        public System.Data.DataSet GetUtentiSostituti(int nUserId) {
            return base.Channel.GetUtentiSostituti(nUserId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUtentiSostitutiAsync(int nUserId) {
            return base.Channel.GetUtentiSostitutiAsync(nUserId);
        }
        
        public System.Data.DataSet GetUtentiSostituitiAppl(int nUserId, string sApplicazione) {
            return base.Channel.GetUtentiSostituitiAppl(nUserId, sApplicazione);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUtentiSostituitiApplAsync(int nUserId, string sApplicazione) {
            return base.Channel.GetUtentiSostituitiApplAsync(nUserId, sApplicazione);
        }
        
        public System.Data.DataSet GetResponsabiliStrutture() {
            return base.Channel.GetResponsabiliStrutture();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetResponsabiliStruttureAsync() {
            return base.Channel.GetResponsabiliStruttureAsync();
        }
        
        public System.Data.DataSet GetResponsabiliStruttureConDate() {
            return base.Channel.GetResponsabiliStruttureConDate();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetResponsabiliStruttureConDateAsync() {
            return base.Channel.GetResponsabiliStruttureConDateAsync();
        }
        
        public System.Data.DataSet GetStruttureConDate() {
            return base.Channel.GetStruttureConDate();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetStruttureConDateAsync() {
            return base.Channel.GetStruttureConDateAsync();
        }
        
        public System.Data.DataSet GetStruttureUtente(int nUserId) {
            return base.Channel.GetStruttureUtente(nUserId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetStruttureUtenteAsync(int nUserId) {
            return base.Channel.GetStruttureUtenteAsync(nUserId);
        }
        
        public System.Data.DataSet GetUtentiStruttura(int nIdStruttura) {
            return base.Channel.GetUtentiStruttura(nIdStruttura);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUtentiStrutturaAsync(int nIdStruttura) {
            return base.Channel.GetUtentiStrutturaAsync(nIdStruttura);
        }
        
        public System.Data.DataSet GetAllStruttureUtente(int nUserId) {
            return base.Channel.GetAllStruttureUtente(nUserId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllStruttureUtenteAsync(int nUserId) {
            return base.Channel.GetAllStruttureUtenteAsync(nUserId);
        }
        
        public System.Data.DataSet GetAllStruttureUtenteConDate(int nUserId) {
            return base.Channel.GetAllStruttureUtenteConDate(nUserId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllStruttureUtenteConDateAsync(int nUserId) {
            return base.Channel.GetAllStruttureUtenteConDateAsync(nUserId);
        }
        
        public System.Data.DataSet GetStruttureSenzaResponsabile() {
            return base.Channel.GetStruttureSenzaResponsabile();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetStruttureSenzaResponsabileAsync() {
            return base.Channel.GetStruttureSenzaResponsabileAsync();
        }
        
        public System.Data.DataSet GetUserDepAppProfiles(int nUserId, string sApplication) {
            return base.Channel.GetUserDepAppProfiles(nUserId, sApplication);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUserDepAppProfilesAsync(int nUserId, string sApplication) {
            return base.Channel.GetUserDepAppProfilesAsync(nUserId, sApplication);
        }
        
        public System.Data.DataSet GetAllUtentiStruttura(int nIdStruttura) {
            return base.Channel.GetAllUtentiStruttura(nIdStruttura);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllUtentiStrutturaAsync(int nIdStruttura) {
            return base.Channel.GetAllUtentiStrutturaAsync(nIdStruttura);
        }
        
        public System.Data.DataSet GetAllUtentiInterniStruttura(int nIdStruttura) {
            return base.Channel.GetAllUtentiInterniStruttura(nIdStruttura);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllUtentiInterniStrutturaAsync(int nIdStruttura) {
            return base.Channel.GetAllUtentiInterniStrutturaAsync(nIdStruttura);
        }
        
        public System.Data.DataSet GetAllUtentiInterniStrutturaPerData(int nIdStruttura) {
            return base.Channel.GetAllUtentiInterniStrutturaPerData(nIdStruttura);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllUtentiInterniStrutturaPerDataAsync(int nIdStruttura) {
            return base.Channel.GetAllUtentiInterniStrutturaPerDataAsync(nIdStruttura);
        }
        
        public System.Data.DataSet GetUtentiPerFunzione(string sCodElFunz) {
            return base.Channel.GetUtentiPerFunzione(sCodElFunz);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUtentiPerFunzioneAsync(string sCodElFunz) {
            return base.Channel.GetUtentiPerFunzioneAsync(sCodElFunz);
        }
        
        public System.Data.DataSet GetFunzioniPerUtente(int nIdUtente) {
            return base.Channel.GetFunzioniPerUtente(nIdUtente);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetFunzioniPerUtenteAsync(int nIdUtente) {
            return base.Channel.GetFunzioniPerUtenteAsync(nIdUtente);
        }
        
        public System.Data.DataSet GetUtentePerCodice(int nIdUtente) {
            return base.Channel.GetUtentePerCodice(nIdUtente);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUtentePerCodiceAsync(int nIdUtente) {
            return base.Channel.GetUtentePerCodiceAsync(nIdUtente);
        }
        
        public System.Data.DataSet GetPosOrgStrutOrg(int nIdPosOrg) {
            return base.Channel.GetPosOrgStrutOrg(nIdPosOrg);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPosOrgStrutOrgAsync(int nIdPosOrg) {
            return base.Channel.GetPosOrgStrutOrgAsync(nIdPosOrg);
        }
        
        public System.Data.DataSet GetAllStrutture() {
            return base.Channel.GetAllStrutture();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllStruttureAsync() {
            return base.Channel.GetAllStruttureAsync();
        }
        
        public System.Data.DataSet GetAllStrutture_Tutte() {
            return base.Channel.GetAllStrutture_Tutte();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllStrutture_TutteAsync() {
            return base.Channel.GetAllStrutture_TutteAsync();
        }
        
        public System.Data.DataSet GetAllUffici() {
            return base.Channel.GetAllUffici();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllUfficiAsync() {
            return base.Channel.GetAllUfficiAsync();
        }
        
        public System.Data.DataSet GetSedeUtentePerCodice(int nIdUtente) {
            return base.Channel.GetSedeUtentePerCodice(nIdUtente);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSedeUtentePerCodiceAsync(int nIdUtente) {
            return base.Channel.GetSedeUtentePerCodiceAsync(nIdUtente);
        }
        
        public System.Data.DataSet GetSottopostiDaResponsabile(int nIdUtente) {
            return base.Channel.GetSottopostiDaResponsabile(nIdUtente);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSottopostiDaResponsabileAsync(int nIdUtente) {
            return base.Channel.GetSottopostiDaResponsabileAsync(nIdUtente);
        }
        
        public System.Data.DataSet GetAllSedi() {
            return base.Channel.GetAllSedi();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllSediAsync() {
            return base.Channel.GetAllSediAsync();
        }
        
        public System.Data.DataSet GetStruttureSede(int nIdSede) {
            return base.Channel.GetStruttureSede(nIdSede);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetStruttureSedeAsync(int nIdSede) {
            return base.Channel.GetStruttureSedeAsync(nIdSede);
        }
        
        public System.Data.DataSet GetAllStruttureResponsabile(int nUserId) {
            return base.Channel.GetAllStruttureResponsabile(nUserId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllStruttureResponsabileAsync(int nUserId) {
            return base.Channel.GetAllStruttureResponsabileAsync(nUserId);
        }
    }
}
